spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/FootwaredRedux
        username: postgres
        password: 1508
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
    properties:
        hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
    level:
        org.springframework.security: trace
